<?php
/**
 * Homepage Instagram feed shortcode setting.
 *
 * @package Rectify_Custom
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! function_exists( 'rectify_custom_sanitize_homepage_instagram_shortcode' ) ) {
	/**
	 * Accept one complete Smash Balloon Instagram Feed shortcode.
	 *
	 * @param mixed $value Submitted meta value.
	 * @return string
	 */
	function rectify_custom_sanitize_homepage_instagram_shortcode( $value ) {
		if ( ! is_string( $value ) ) {
			return '';
		}

		$value = trim( wp_strip_all_tags( $value ) );

		if ( '' === $value ) {
			return '';
		}

		$pattern = get_shortcode_regex( array( 'instagram-feed' ) );

		if ( preg_match( '#^' . $pattern . '$#s', $value, $matches ) && 'instagram-feed' === $matches[2] ) {
			return $value;
		}

		return '';
	}
}

if ( ! function_exists( 'rectify_custom_register_homepage_instagram_meta' ) ) {
	/**
	 * Register the setting for REST/editor compatibility.
	 */
	function rectify_custom_register_homepage_instagram_meta() {
		register_post_meta(
			'page',
			'_rectify_homepage_instagram_shortcode',
			array(
				'type'              => 'string',
				'single'            => true,
				'default'           => '',
				'show_in_rest'      => true,
				'sanitize_callback' => 'rectify_custom_sanitize_homepage_instagram_shortcode',
				'auth_callback'     => static function () {
					return current_user_can( 'edit_pages' );
				},
			)
		);
	}
}
add_action( 'init', 'rectify_custom_register_homepage_instagram_meta', 11 );

if ( ! function_exists( 'rectify_custom_add_homepage_instagram_metabox' ) ) {
	/**
	 * Add the setting only to pages using the Rectify homepage template.
	 *
	 * @param WP_Post $post Current page.
	 */
	function rectify_custom_add_homepage_instagram_metabox( $post ) {
		if ( 'page-rectify-homepage.php' !== get_page_template_slug( $post->ID ) ) {
			return;
		}

		add_meta_box(
			'rectify-homepage-instagram-feed',
			__( 'Homepage – Instagram Feed', 'rectify-custom' ),
			'rectify_custom_render_homepage_instagram_metabox',
			'page',
			'normal',
			'default'
		);
	}
}
add_action( 'add_meta_boxes_page', 'rectify_custom_add_homepage_instagram_metabox' );

if ( ! function_exists( 'rectify_custom_render_homepage_instagram_metabox' ) ) {
	/**
	 * Render the homepage Instagram feed setting.
	 *
	 * @param WP_Post $post Current page.
	 */
	function rectify_custom_render_homepage_instagram_metabox( $post ) {
		$shortcode = get_post_meta( $post->ID, '_rectify_homepage_instagram_shortcode', true );

		wp_nonce_field( 'rectify_save_homepage_instagram_shortcode', 'rectify_homepage_instagram_nonce' );
		?>
		<p>
			<label for="rectify-homepage-instagram-shortcode">
				<strong><?php esc_html_e( 'Instagram Feed Shortcode', 'rectify-custom' ); ?></strong>
			</label>
		</p>
		<input
			type="text"
			id="rectify-homepage-instagram-shortcode"
			name="rectify_homepage_instagram_shortcode"
			class="widefat"
			value="<?php echo esc_attr( $shortcode ); ?>"
			placeholder="[instagram-feed feed=1]"
		/>
		<p class="description">
			<?php esc_html_e( 'Paste a shortcode generated by Instagram Feed. When set, it replaces the project cards in “Follow Our Latest Projects & Insights”. Leave it empty to use the existing project grid.', 'rectify-custom' ); ?>
		</p>
		<?php if ( ! shortcode_exists( 'instagram-feed' ) ) : ?>
			<p>
				<strong><?php esc_html_e( 'Instagram Feed is currently inactive, so the project grid will remain visible.', 'rectify-custom' ); ?></strong>
			</p>
		<?php endif; ?>
		<?php
	}
}

if ( ! function_exists( 'rectify_custom_save_homepage_instagram_shortcode' ) ) {
	/**
	 * Save the homepage Instagram feed setting.
	 *
	 * @param int $post_id Page ID.
	 */
	function rectify_custom_save_homepage_instagram_shortcode( $post_id ) {
		if (
			! isset( $_POST['rectify_homepage_instagram_nonce'] )
			|| ! wp_verify_nonce(
				sanitize_text_field( wp_unslash( $_POST['rectify_homepage_instagram_nonce'] ) ),
				'rectify_save_homepage_instagram_shortcode'
			)
		) {
			return;
		}

		if ( ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) || wp_is_post_revision( $post_id ) ) {
			return;
		}

		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}

		$shortcode = isset( $_POST['rectify_homepage_instagram_shortcode'] )
			? rectify_custom_sanitize_homepage_instagram_shortcode( wp_unslash( $_POST['rectify_homepage_instagram_shortcode'] ) )
			: '';

		if ( '' === $shortcode ) {
			delete_post_meta( $post_id, '_rectify_homepage_instagram_shortcode' );
			return;
		}

		update_post_meta( $post_id, '_rectify_homepage_instagram_shortcode', $shortcode );
	}
}
add_action( 'save_post_page', 'rectify_custom_save_homepage_instagram_shortcode' );

if ( ! function_exists( 'rectify_custom_render_homepage_instagram_images_immediately' ) ) {
	/**
	 * Render the homepage feed images in the initial HTML.
	 *
	 * Smash Balloon normally prints white placeholder images and replaces them
	 * with JavaScript. On the homepage that creates blank tiles while scripts are
	 * delayed or blocked. Its no-JS mode prints the selected image URLs directly.
	 * Disable its automatic consent-plugin placeholder for this feed because the
	 * missing resize cache requires those source URLs to be rendered directly.
	 *
	 * Local image resizing is switched off for the same reason. It also stops the
	 * plugin from rebuilding the local header avatar on every homepage request,
	 * which ran wp_get_image_editor() against the Instagram CDN URL and made
	 * exif_imagetype() emit a "Error reading from https://scontent.cdninstagram…"
	 * notice whenever that remote read failed. The header now uses the source
	 * avatar URL, matching the images in the feed itself.
	 *
	 * @param array $settings Instagram Feed database settings.
	 * @return array
	 */
	function rectify_custom_render_homepage_instagram_images_immediately( $settings ) {
		if ( ! is_admin() && is_front_page() ) {
			$settings['disable_js_image_loading']     = true;
			$settings['gdpr']                        = 'no';
			$settings['sb_instagram_disable_resize'] = 'on';
		}

		return $settings;
	}
}
add_filter( 'sbi_database_settings', 'rectify_custom_render_homepage_instagram_images_immediately' );

if ( ! function_exists( 'rectify_custom_match_homepage_instagram_profile_grid' ) ) {
	/**
	 * Render the homepage feed as an even four-column by two-row grid while
	 * retaining Instagram's current 3:4 profile-thumbnail geometry.
	 *
	 * Feed Builder settings are applied after the global database settings, so
	 * this later filter is the correct place to override the saved square,
	 * four-column presentation for this page only.
	 *
	 * @param array $settings Instagram Feed render settings.
	 * @return array
	 */
	function rectify_custom_match_homepage_instagram_profile_grid( $settings ) {
		if ( ! is_admin() && is_front_page() ) {
			$settings['cols']             = 4;
			$settings['colstablet']       = 4;
			$settings['colsmobile']       = 2;
			$settings['imageaspectratio'] = '3:4';
		}

		return $settings;
	}
}
add_filter( 'sbi_feed_settings', 'rectify_custom_match_homepage_instagram_profile_grid' );

if ( ! function_exists( 'rectify_custom_bypass_homepage_instagram_resize_cache' ) ) {
	/**
	 * Use the Instagram source image when the homepage feed is rendered.
	 *
	 * The resized-image records can survive a deployment even when the
	 * generated files in uploads/sb-instagram-feed-images do not. Smash
	 * Balloon then renders those stale local URLs and every thumbnail 404s.
	 * Treating image resizing as disabled for this one feed makes the plugin
	 * use the current source URL already stored with each post instead.
	 *
	 * @param bool  $disabled Whether local image resizing is disabled.
	 * @param mixed $data     Optional feed data supplied by the plugin.
	 * @return bool
	 */
	function rectify_custom_bypass_homepage_instagram_resize_cache( $disabled, $data = false ) {
		unset( $data );

		if ( ! is_admin() && is_front_page() ) {
			return true;
		}

		return $disabled;
	}
}
add_filter( 'sbi_image_resizing_disabled', 'rectify_custom_bypass_homepage_instagram_resize_cache', 10, 2 );

if ( ! function_exists( 'rectify_custom_get_homepage_instagram_shortcode' ) ) {
	/**
	 * Get the validated Instagram Feed shortcode for a page.
	 *
	 * @param int $post_id Page ID.
	 * @return string
	 */
	function rectify_custom_get_homepage_instagram_shortcode( $post_id ) {
		return rectify_custom_sanitize_homepage_instagram_shortcode(
			get_post_meta( $post_id, '_rectify_homepage_instagram_shortcode', true )
		);
	}
}
